/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppQuarterlyRouteImport } from './routes/_app/quarterly'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppInstitutionsRouteImport } from './routes/_app/institutions'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppExportsRouteImport } from './routes/_app/exports'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBusinessAreasRouteImport } from './routes/_app/business-areas'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppOpportunitiesIdRouteImport } from './routes/_app/opportunities.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminInstitutionsRouteImport } from './routes/_app/admin/institutions'
import { Route as AppAdminBusinessAreasRouteImport } from './routes/_app/admin/business-areas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuarterlyRoute = AppQuarterlyRouteImport.update({
  id: '/quarterly',
  path: '/quarterly',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionsRoute = AppInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessAreasRoute = AppBusinessAreasRouteImport.update({
  id: '/business-areas',
  path: '/business-areas',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesIdRoute = AppOpportunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOpportunitiesRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminInstitutionsRoute = AppAdminInstitutionsRouteImport.update({
  id: '/admin/institutions',
  path: '/admin/institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBusinessAreasRoute = AppAdminBusinessAreasRouteImport.update({
  id: '/admin/business-areas',
  path: '/admin/business-areas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/business-areas': typeof AppBusinessAreasRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/exports': typeof AppExportsRoute
  '/import': typeof AppImportRoute
  '/institutions': typeof AppInstitutionsRoute
  '/notifications': typeof AppNotificationsRoute
  '/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/pipeline': typeof AppPipelineRoute
  '/quarterly': typeof AppQuarterlyRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/business-areas': typeof AppAdminBusinessAreasRoute
  '/admin/institutions': typeof AppAdminInstitutionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/business-areas': typeof AppBusinessAreasRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/exports': typeof AppExportsRoute
  '/import': typeof AppImportRoute
  '/institutions': typeof AppInstitutionsRoute
  '/notifications': typeof AppNotificationsRoute
  '/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/pipeline': typeof AppPipelineRoute
  '/quarterly': typeof AppQuarterlyRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/business-areas': typeof AppAdminBusinessAreasRoute
  '/admin/institutions': typeof AppAdminInstitutionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/business-areas': typeof AppBusinessAreasRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/exports': typeof AppExportsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/institutions': typeof AppInstitutionsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/opportunities': typeof AppOpportunitiesRouteWithChildren
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/quarterly': typeof AppQuarterlyRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/admin/business-areas': typeof AppAdminBusinessAreasRoute
  '/_app/admin/institutions': typeof AppAdminInstitutionsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/opportunities/$id': typeof AppOpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/business-areas'
    | '/calendar'
    | '/dashboard'
    | '/exports'
    | '/import'
    | '/institutions'
    | '/notifications'
    | '/opportunities'
    | '/pipeline'
    | '/quarterly'
    | '/reports'
    | '/settings'
    | '/admin/business-areas'
    | '/admin/institutions'
    | '/admin/users'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/business-areas'
    | '/calendar'
    | '/dashboard'
    | '/exports'
    | '/import'
    | '/institutions'
    | '/notifications'
    | '/opportunities'
    | '/pipeline'
    | '/quarterly'
    | '/reports'
    | '/settings'
    | '/admin/business-areas'
    | '/admin/institutions'
    | '/admin/users'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/business-areas'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/exports'
    | '/_app/import'
    | '/_app/institutions'
    | '/_app/notifications'
    | '/_app/opportunities'
    | '/_app/pipeline'
    | '/_app/quarterly'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/admin/business-areas'
    | '/_app/admin/institutions'
    | '/_app/admin/users'
    | '/_app/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quarterly': {
      id: '/_app/quarterly'
      path: '/quarterly'
      fullPath: '/quarterly'
      preLoaderRoute: typeof AppQuarterlyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institutions': {
      id: '/_app/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof AppInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exports': {
      id: '/_app/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business-areas': {
      id: '/_app/business-areas'
      path: '/business-areas'
      fullPath: '/business-areas'
      preLoaderRoute: typeof AppBusinessAreasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities/$id': {
      id: '/_app/opportunities/$id'
      path: '/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof AppOpportunitiesIdRouteImport
      parentRoute: typeof AppOpportunitiesRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/institutions': {
      id: '/_app/admin/institutions'
      path: '/admin/institutions'
      fullPath: '/admin/institutions'
      preLoaderRoute: typeof AppAdminInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/business-areas': {
      id: '/_app/admin/business-areas'
      path: '/admin/business-areas'
      fullPath: '/admin/business-areas'
      preLoaderRoute: typeof AppAdminBusinessAreasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppOpportunitiesRouteChildren {
  AppOpportunitiesIdRoute: typeof AppOpportunitiesIdRoute
}

const AppOpportunitiesRouteChildren: AppOpportunitiesRouteChildren = {
  AppOpportunitiesIdRoute: AppOpportunitiesIdRoute,
}

const AppOpportunitiesRouteWithChildren =
  AppOpportunitiesRoute._addFileChildren(AppOpportunitiesRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBusinessAreasRoute: typeof AppBusinessAreasRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportsRoute: typeof AppExportsRoute
  AppImportRoute: typeof AppImportRoute
  AppInstitutionsRoute: typeof AppInstitutionsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRouteWithChildren
  AppPipelineRoute: typeof AppPipelineRoute
  AppQuarterlyRoute: typeof AppQuarterlyRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminBusinessAreasRoute: typeof AppAdminBusinessAreasRoute
  AppAdminInstitutionsRoute: typeof AppAdminInstitutionsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBusinessAreasRoute: AppBusinessAreasRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportsRoute: AppExportsRoute,
  AppImportRoute: AppImportRoute,
  AppInstitutionsRoute: AppInstitutionsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRouteWithChildren,
  AppPipelineRoute: AppPipelineRoute,
  AppQuarterlyRoute: AppQuarterlyRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminBusinessAreasRoute: AppAdminBusinessAreasRoute,
  AppAdminInstitutionsRoute: AppAdminInstitutionsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
