/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppInstitutionsRouteImport } from './routes/_app/institutions'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBusinessAreasRouteImport } from './routes/_app/business-areas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutionsRoute = AppInstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessAreasRoute = AppBusinessAreasRouteImport.update({
  id: '/business-areas',
  path: '/business-areas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/business-areas': typeof AppBusinessAreasRoute
  '/dashboard': typeof AppDashboardRoute
  '/institutions': typeof AppInstitutionsRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/business-areas': typeof AppBusinessAreasRoute
  '/dashboard': typeof AppDashboardRoute
  '/institutions': typeof AppInstitutionsRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/business-areas': typeof AppBusinessAreasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/institutions': typeof AppInstitutionsRoute
  '/_app/reports': typeof AppReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/business-areas'
    | '/dashboard'
    | '/institutions'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/business-areas'
    | '/dashboard'
    | '/institutions'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/business-areas'
    | '/_app/dashboard'
    | '/_app/institutions'
    | '/_app/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institutions': {
      id: '/_app/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof AppInstitutionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business-areas': {
      id: '/_app/business-areas'
      path: '/business-areas'
      fullPath: '/business-areas'
      preLoaderRoute: typeof AppBusinessAreasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBusinessAreasRoute: typeof AppBusinessAreasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInstitutionsRoute: typeof AppInstitutionsRoute
  AppReportsRoute: typeof AppReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBusinessAreasRoute: AppBusinessAreasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInstitutionsRoute: AppInstitutionsRoute,
  AppReportsRoute: AppReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
